### ISSUE TITLE
check_build_tools doesn't search path in RStudio on Windows

### ISSUE THREAD

**Issue by karldw** [r-lib/pkgbuild#15]
Running `check_build_tools` works in an basic RTerm environment, but fails when run in RStudio.  I've installed RTools in a non-standard place, in my user folder rather than `C:\rtools`.  In RStudio, `check_build_tools` launches a pop-up asking me to download Rtools. When I click no, I get the error "Error: Could not find tools necessary to compile a package".

I'm using pkgbuild r-lib/pkgbuild@6574561, RStudio 1.0.153, R 3.4.1 and RTools 3.4.

**Comment by jimhester** [comment]
This sounds like an issue with the IDE rather than pkgbuild, as the dialog is generated by the IDE when it cannot find build tools (it uses a separate code path for detection than is used in pkgbuild).

The output of the following would likely be useful to debug the issue.

```r
pkgbuild::find_rtools(debug = TRUE)
```

@kevinushey any input on the best way to debug this from the IDE?

**Comment by kevinushey** [comment]
Here's the associated IDE code path:

https://github.com/rstudio/rstudio/blob/2918508873ea45343766974d25415c700a5e37fc/src/cpp/session/modules/build/SessionBuildEnvironment.cpp#L100-L195

If you're installing Rtools into a custom location, you'll need to tell Rtools to also update the registry (I don't think this is done by default). Otherwise, you need to manually add it to the PATH yourself.

Honestly, I recommend just letting RStudio install Rtools into the default path, to save yourself from these sorts of headaches.

**Comment by karldw** [comment]
Thank you both!  I've reinstalled R since I opened this issue and `check_build_tools` works now.  Maybe I set my PATH properly this time... 
Sorry for occupying your time debugging this.

If I remember properly, the default is `c:\rtools`, which means non-admin users can't install Rtools to the default location.  That's not an issue to address in pkgbuild, just my pitch for RStudio to support non-default locations.
