### ISSUE TITLE
Check interaction between find_rtools() and RStudio auto installer

### ISSUE THREAD

**Issue by hadley** [r-lib/pkgbuild#25]
Some hints of problems at https://github.com/STAT545-UBC/Discussion/issues/397#issuecomment-258573319

**Comment by jimhester** [comment]
Not sure what action to take with this, I read through most of the discussion

**Comment by hadley** [comment]
I think in an ideal world, you'd start from a blank slate on a windows VM, and check what happens when you try and build a package with a src directory.

**Comment by jimhester** [comment]
This actually seems to work pretty well

**Comment by hadley** [comment]
I wonder why we seem to be seeing problems in the wild. Maybe just because devtools was binding to the wrong function?

**Comment by jimhester** [comment]
I would guess a few things.

- People sometimes do crazy things with the `PATH`
- in the wild was using CRAN devtools rather than pkgbuild, I think the story is a bit better now
- I was using the latest RTools, and I think Jeroen has smoothed over some of the issues there
- I was using last released RStudio, again probably some issues resolved

But with all of the above RStudio automatically prompts and installs RTools when `pkgbuild::has_build_tools()` is run, and outside of RStudio you get a informative prompt.

**Comment by hadley** [comment]
Ok, sounds good 😄
