### ISSUE TITLE
Fix configure/cleanup execute bit?

### ISSUE THREAD

**Issue by gaborcsardi** [r-lib/pkgbuild#66]
If you download a tar.gz package and then install it, the builtin tar implementation (!) fixes the execute permissions for the `configure` /  `cleanup` files: https://github.com/wch/r-source/blob/5b2f6807839f2970051f6723040a27bb97a49c81/src/library/utils/R/tar.R#L470

This is in tar, not in untar, so it happens when R is tarring up a built package.

This is sometimes a problem, e.g. when you download a zip repo archive from GitHub, which does not have executable bits, and the R package has dynamic manual pages. In this case R tries to install the package before building it (!), and fails if `configure` is not executable.

I am not sure why but `R CMD build --no-manual` does not help, either:
```
❯ R CMD build --no-manual  r-lib-ps-7d17711
* checking for file ‘r-lib-ps-7d17711/DESCRIPTION’ ... OK
* preparing ‘ps’:
* checking DESCRIPTION meta-information ... OK
* cleaning src
* installing the package to process help pages
      -----------------------------------
* installing *source* package ‘ps’ ...
ERROR: 'configure' exists but is not executable -- see the 'R Installation and Administration Manual'
* removing ‘/private/var/folders/59/0gkmw1yj2w7bf2dfc3jznv5w0000gn/T/Rtmp4TcYrg/Rinst1667631fb8710/ps’
      -----------------------------------
ERROR: package installation failed
```

So my question is, should pkgbuild try to fix up the `configure` and  `cleanup` files at the beginning? I think this would make sense, certainly more sense than fixing them in the tar implementation.

**Comment by gaborcsardi** [comment]
@jimhester what do you think?

**Comment by jimhester** [comment]
This is one of the reasons we switched to downloading tar files in remotes rather than zip files.

Even if pkgbuild does fix the top level `configure` and `cleanup` files you can still run into issues if there are other scripts which should be executable, e.g. https://github.com/r-lib/devtools/issues/1799

And actually IIRC the zip archive from GitHub _does_ store the executable status of the files, if you unzip the archive manually on macOS you will see they are set, but R's unzip does not use the information.

**Comment by gaborcsardi** [comment]
Right. My issue with the internal tar is that it is so sloooooow. But yeah, good point about executables. Ultimately, I'll finish the tar package, or will add unzip capabilities to the zip package.

We can also try to patch R's unzip, I don't know what lib they are using. Anyway, I'll close this now.
