### ISSUE TITLE
Warn users RTools is _not_ appropriately configured if not in system PATH variable

### ISSUE THREAD

**Issue by coatless** [r-lib/pkgbuild#8]
The [`find_rtools()`](https://github.com/r-lib/pkgbuild/blob/8aab60b03bb09212881e3544e332d60defc52fd6/R/rtools.r#L111) feature is problematic because if _Rtools_ is detected within the registry it indicates that _Rtools_ has been installed correctly. However, this makes the critical assumption that every time a new session is created `find_rtools()` is run to re-register the location of _Rtools_ as `find_rtools` only performs a **per session** modification. Many users, when they go to compile code in an _R_ session or _RMarkdown_ documents encounter an issue as a result. Examples:

- [SO: Why do I need to run find_rtools() before has_devel() = TRUE?](https://stackoverflow.com/questions/37226661/why-do-i-need-to-run-find-rtools-before-has-devel-true/37229234#37229234)
- [SO: Knitr and Rcpp error 1 ocurred while building shared library](https://stackoverflow.com/questions/44874630/knitr-and-rcpp-error-1-ocurred-while-building-shared-library)
- [SO: Can't use Rcpp engine in R Markdown](https://stackoverflow.com/questions/39456577/cant-use-rcpp-engine-in-r-markdown)

Proposed solution: Add a warning after [Line 111 in rtools.R](https://github.com/r-lib/pkgbuild/blob/8aab60b03bb09212881e3544e332d60defc52fd6/R/rtools.r#L111) containing:

```r
message("WARNING: Rtools was not found on the system PATH.\n\n",
        "However, there was a valid entry for Rtools in the registry.\n\n",
        "As a result, Rtools will only be available on a per-session basis after",
        "running find_rtools.\n\n",
        "Please download and reinstall ", rtools_needed(), " from ", rtools_url,".\n\n"
        "Make sure to add Rtools to your PATH!")
```

**Comment by hadley** [comment]
In general you should **not** modify the system path and `find_rtools()` is supposed to be session specific.  

I think the root cause of the three SO issue that you link to is that while RStudio and devtools try to be helpful and get you set up with the Rtools, Rcpp does not. But I think we should be handling the knitr cases; I'll pass that on to the IDE team.

**Comment by JoFAM** [comment]
@hadley I find that a very odd statement. Per https://cran.r-project.org/doc/manuals/R-admin.html#The-Windows-toolset the manual specifically tells you to modify the system path. If the system path is not set correctly, rtools is not guaranteed to work correctly.

I fail to see the link with Rcpp other than that people asking the question ran into problems when using Rcpp.

**Comment by eddelbuettel** [comment]
A friend pointed me to this (by now) old thread, and I just wanted to add that pointing to Rcpp is complete nonsense as Rcpp has nothing to do with _how `Rtools` is installed_.   This system is layered:  while Rtools is used by Rcpp the reverse is not true as Depends: are graphs without cycles.

And while I typed this @JoFAM just made the same statement...

**Comment by hadley** [comment]
Setting the system path is not a good approach because it implies that there is one version of R-tools installed for one version of R. This is often not true. Additionally it can cause problems with other tools that also mess with the system path. The approach of setting the path on a per session process has worked for both RStudio and devtools for a long time for a large number of people.

I do not remember the context of this issue, so I apologise if I made factually incorrect statements about Rcpp.

**Comment by eddelbuettel** [comment]
> Setting the system path is not a good approach

But isn't that precisely what [R Installation and Administration](https://cran.r-project.org/doc/manuals/r-release/R-admin.html#The-Windows-toolset) suggests, and what the R Installer does?

**Comment by hadley** [comment]
Yes, but experience has shown that that is not the best approach. Devtools copies what RStudio does, and I trust JJ's experience/knowledge here. 

(Plus, IIRC, you have to opt-in to setting the path in the installer, and many people don't)

**Comment by eddelbuettel** [comment]
You have to opt-into many things, including to not install in paths with spaces.  So that is not a valid argument.

It is also not a valid argument _in the context of R use_ to debate around what the installation manual itself suggests.   In essence you are defining YOUR world anew whereas the original bug reports wants helps for larger world as whole.   You cannot close that as incorrect, but you are free to say (as you do) that don't give a fiver.

**Comment by hadley** [comment]
This discussion seems to be veering in an unproductive discussion and far away from the original issue, so I'm going to lock it.
